### ISSUE TITLE
[Bug]: Animatediff version 2.0.0 does not work well with Control net version 1.1.441

### ISSUE THREAD

**Issue by ai-is-in-wonderland** [continue-revolution/sd-webui-animatediff#476]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

I used Animatediff version 2.0.0 and confirmed that it does not work well with Control net version 1.1.441. Also, I believe that the image quality has significantly deteriorated compared to before, even without using Control net. I am looking forward to the development of Animatediff, so please keep up the good work.

### Steps to reproduce the problem

no

### What should have happened?

no

### Commit where the problem happens

webui: A1111 ver 1.8.0
extension: 

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
*** Error running process: C:\stablediffusion20230811\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "C:\stablediffusion20230811\stable-diffusion-webui\modules\scripts.py", line 784, in process
        script.process(p, *script_args)
      File "C:\stablediffusion20230811\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1279, in process
        self.controlnet_hack(p)
      File "C:\stablediffusion20230811\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1264, in controlnet_hack
        self.controlnet_main_entry(p)
      File "C:\stablediffusion20230811\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 248, in hacked_main_entry
        model_net.reset()
    AttributeError: 'ControlModel' object has no attribute 'reset'
```

### Additional information

 no

**Comment by continue-revolution** [comment]
You have failed to update animatediff extension. 2.0.0 and later does not have animatediff_cn.py

**Comment by ai-is-in-wonderland** [comment]
It seems that it's not possible to update using the normal "check for updates" and "apply and restart UI" methods. After removing the previous version and installing it anew, I was able to install the new version. With the new version, the control net worked correctly. I will share this information with Japanese user on my YouTube channel(@AI_is_in_wonderland). Thank you for your prompt response. 
I have another request: please consider supporting the animatedifflcm model. The model's URL is https://huggingface.co/wangfuyun/AnimateLCM/tree/main. 
I'm looking forward to future developments.

**Comment by continue-revolution** [comment]
1. Thanks for your sharing. Most likely you modified some scripts in my extension so git refuse to perform any updates.
2. Yes, AnimateLCM will be supported with a medium priority. The current highest priority will be to fix all the bugs in sd-forge-animatediff, and AnimateLCM should come after that.
